// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: loan.proto

package loanpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        int64                  `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanRequest) Reset() {
	*x = CreateLoanRequest{}
	mi := &file_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequest) ProtoMessage() {}

func (x *CreateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoanRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateLoanRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        int64                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanResponse) Reset() {
	*x = CreateLoanResponse{}
	mi := &file_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanResponse) ProtoMessage() {}

func (x *CreateLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateLoanResponse) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *CreateLoanResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLoanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanRequest) Reset() {
	*x = GetLoanRequest{}
	mi := &file_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanRequest) ProtoMessage() {}

func (x *GetLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanRequest.ProtoReflect.Descriptor instead.
func (*GetLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoanRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        int64                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanResponse) Reset() {
	*x = GetLoanResponse{}
	mi := &file_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanResponse) ProtoMessage() {}

func (x *GetLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanResponse.ProtoReflect.Descriptor instead.
func (*GetLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoanResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLoanResponse) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *GetLoanResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLoanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_loan_proto protoreflect.FileDescriptor

const file_loan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"loan.proto\x12\x06loanpb\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x11CreateLoanRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\x03R\x06bookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"n\n" +
	"\x12CreateLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\" \n" +
	"\x0eGetLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"k\n" +
	"\x0fGetLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xbc\x01\n" +
	"\vLoanService\x12Y\n" +
	"\n" +
	"CreateLoan\x12\x19.loanpb.CreateLoanRequest\x1a\x1a.loanpb.CreateLoanResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/loans\x12R\n" +
	"\aGetLoan\x12\x16.loanpb.GetLoanRequest\x1a\x17.loanpb.GetLoanResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/loans/{id}B\x0eZ\fproto/loanpbb\x06proto3"

var (
	file_loan_proto_rawDescOnce sync.Once
	file_loan_proto_rawDescData []byte
)

func file_loan_proto_rawDescGZIP() []byte {
	file_loan_proto_rawDescOnce.Do(func() {
		file_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)))
	})
	return file_loan_proto_rawDescData
}

var file_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_loan_proto_goTypes = []any{
	(*CreateLoanRequest)(nil),  // 0: loanpb.CreateLoanRequest
	(*CreateLoanResponse)(nil), // 1: loanpb.CreateLoanResponse
	(*GetLoanRequest)(nil),     // 2: loanpb.GetLoanRequest
	(*GetLoanResponse)(nil),    // 3: loanpb.GetLoanResponse
}
var file_loan_proto_depIdxs = []int32{
	0, // 0: loanpb.LoanService.CreateLoan:input_type -> loanpb.CreateLoanRequest
	2, // 1: loanpb.LoanService.GetLoan:input_type -> loanpb.GetLoanRequest
	1, // 2: loanpb.LoanService.CreateLoan:output_type -> loanpb.CreateLoanResponse
	3, // 3: loanpb.LoanService.GetLoan:output_type -> loanpb.GetLoanResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loan_proto_init() }
func file_loan_proto_init() {
	if File_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_proto_goTypes,
		DependencyIndexes: file_loan_proto_depIdxs,
		MessageInfos:      file_loan_proto_msgTypes,
	}.Build()
	File_loan_proto = out.File
	file_loan_proto_goTypes = nil
	file_loan_proto_depIdxs = nil
}
